# Generated by Django 6.0.4 on 2026-05-04 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('outerwear', 'Outerwear'), ('accessories', 'Accessories')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clothes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
