# Generated by Django 6.0.4 on 2026-05-20 18:03
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0003_category_alter_clothingitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wardrobe.category",
            ),
        ),
    ]
