# Generated by Django 6.0.4 on 2026-05-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0005_remove_clothingitemtag_pk_clothingitemtag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.clothingitem')),
            ],
        ),
        migrations.CreateModel(
            name='AiRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='wardrobe.clothingitem')),
                ('recommended_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='wardrobe.clothingitem')),
            ],
        ),
    ]
