# Generated by Django 6.0.4 on 2026-05-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='best_match',
            field=models.BooleanField(default=False),
        ),
    ]
