# Generated by Django 6.0.4 on 2026-05-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_alter_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitemtag',
            name='pk',
        ),
        migrations.AddField(
            model_name='clothingitemtag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
