# Generated by Django 6.0.4 on 2026-05-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_category_user_alter_category_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='clothing/'),
        ),
    ]
