# Generated by Django 6.0.4 on 2026-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_remove_clothingitem_image_url_clothingitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
