# Generated by Django 6.0.4 on 2026-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0009_clothingitem_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='clothing/'),
        ),
    ]
