# Generated by Django 6.0.4 on 2026-05-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_remove_clothingitemtag_pk_clothingitemtag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecommendationitem',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='savedrecommendationitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='SavedRecommendation',
        ),
        migrations.DeleteModel(
            name='SavedRecommendationItem',
        ),
    ]
